# Generated by Django 2.0.8 on 2018-09-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('src_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('parent_area',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_areas', to='competitions.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('src_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, null=True)),
                ('plan', models.CharField(max_length=64)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='competitions.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('src_id', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('venue', models.CharField(max_length=64)),
                ('match_day', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('src_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(null=True)),
                ('country_of_birth', models.CharField(max_length=64, null=True)),
                ('nationality', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('winner', models.CharField(max_length=32, null=True)),
                ('duration', models.CharField(max_length=32, null=True)),
                ('full_time', models.CharField(max_length=8, null=True)),
                ('half_time', models.CharField(max_length=8, null=True)),
                ('extra_time', models.CharField(max_length=8, null=True)),
                ('penalties', models.CharField(max_length=8, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.Match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srd_id', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_match_day', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('src_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('tla', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('founded', models.PositiveIntegerField()),
                ('colors', models.CharField(max_length=64)),
                ('venue', models.CharField(max_length=64, null=True)),
                ('active_competitions', models.ManyToManyField(related_name='teams', to='competitions.Competition')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='competitions.Position'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='competitions.Role'),
        ),
        migrations.AddField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='competitions.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.Competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='competitions.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='referees',
            field=models.ManyToManyField(blank=True, to='competitions.Member'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.Season'),
        ),
        migrations.AddField(
            model_name='competition',
            name='current_season',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.Season'),
        ),
        migrations.AddField(
            model_name='competition',
            name='seasons',
            field=models.ManyToManyField(related_name='_competition_seasons_+', to='competitions.Season'),
        ),
    ]
