# Generated by Django 2.0.8 on 2018-09-04 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0003_auto_20180904_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='team',
            new_name='teams',
        ),
    ]
