# Generated by Django 2.0.8 on 2018-09-04 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0005_auto_20180904_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
